name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: include client config  
        run: |
          echo "$SPOTIFY_CLIENT_ID"  &gt;&gt; cl_id
          echo "$SPOTIFY_CLIENT_SECRET"  &gt;&gt; cl_tk
        shell: bash
        env:
          SPOTIFY_CLIENT_ID : ${{secrets.SPOTIFY_CLIENT_ID}}
          SPOTIFY_CLIENT_SECRET : ${{secrets.SPOTIFY_CLIENT_SECRET}}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/onetagger-autotag:latest